proj/proj/urls.py
from django.contrib import admin
from django.urls import path,include
from projapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('projapp/', include('projapp.urls')),
    path('logout/',views.logout_page,name='logout'),
]

proj/projapp/urls.py
from django.conf.urls import url 
from projapp import views
app_name= 'projapp'
urlpatterns = [
    url('signup/',views.register,name='register'),
    url('login/',views.login_page,name='login')
]

proj/projapp/models.py
from django.db import models

# Create your models here.

proj/projapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    username=forms.CharField(label='Username')
    password1=forms.CharField(widget=forms.PasswordInput(),label='Password')
    password2=forms.CharField(widget=forms.PasswordInput(),label='Password Confirmation')
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

proj/projapp/views.py
from django.shortcuts import render,redirect
from projapp.forms import UserForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
# Create your views here.
def index(request):
    return render(request,'projapp/index.htm')

@csrf_exempt
def register(request):
    registered = False
    form= UserForm
    if request.method == 'POST':
       form= UserForm(request.POST)
       if form.is_valid() :
           form.save()
           registered = True
    return render(request,'projapp/register.htm',{'register':form,
                                                    'registered':registered
    })
def login_page(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user= authenticate(request, username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                messages.info(request,'Invalid Username or password')
        else:
            print("Someone triend to login ")
            print("Username:{} and password: {}".format(username,password))
            return HttpResponse("INVALID DETAILS")
    else:
        return render(request,'projapp/login.htm')

@login_required
def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

proj/templates/projapp/base.htm
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<style>
  .navbar-brand{
    margin-left: 1%;
    margin-right: 3%;
    font-size: x-large;
  }
  nav{
    position: fixed;
    z-index: 1;
  }

</style>
<title>
  {% block title %}
  {% endblock title %}
</title>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Lio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only"></span></a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin <span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'projapp:register' %}">Sign Up</a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'projapp:login' %}">Login</a>
        </li>
      {% endif %}
  </div>
</nav>
<body>
    {% block body_block %}
    
    {% endblock body_block %}
    
</body>
</html>

proj/templates/projapp/index.htm
{% extends 'projapp/base.htm' %}
    {% block title %}
        Home
    {% endblock title %}
    {% block body_block %}
        <h1>Welcome to Us! </h1>
    {% endblock body_block %}

proj/templates/projapp/login.htm
{% extends 'projapp/base.htm' %}
{% load static %}
{% block title %}
Login
{% endblock title %}
{% block body_block %}
<div class="jumbotron">
    <h1> Please Login</h1>
    <form action="{% url 'projapp:login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password" >

        <input type="submit" value="Login">

    </form>
    <div>
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
    </div>
</div>
{% endblock body_block %}

proj/templates/projapp/register.htm
{% extends 'projapp/base.htm' %}
{% load static %}
{% block title %}
    Register
{% endblock title %}

{% block body_block %}
    <style>
        form{
            text-align: center;
            margin: 10%;
        }
    </style>
    <div class="jumbotron">
        
        <form method="POST">
            {% if registered %}
                <h1>Thanks for Registering!</h1>
            {% else %}
                <h1>Registration</h1>
                {{register.as_p}}
                {% csrf_token %}
                <input type="submit" name='Register'>
            {% endif %}
        </form>
        {{form.errors}}
    </div>
 {% endblock body_block %}